### Criar um endereço (PessoaId será nulo)
POST http://localhost:5128/api/enderecos
Content-Type: application/json

{
  "rua": "",
  "cidade": "São Paulo",
  "estado": "SP"
}

###

### Listar todos os endereços
GET http://localhost:5128/api/enderecos

###

### Criar uma pessoa (com EnderecoId existente)
POST http://localhost:5128/api/pessoas
Content-Type: application/json

{
  "nome": "",
  "idade": 30,
  "enderecoId": 9
}

###

### Listar todas as pessoas com o endereço vinculado (objeto completo)
GET http://localhost:5128/api/pessoas

###

### Obter uma pessoa específica
GET http://localhost:5128/api/pessoas/2

###

### Atualizar uma pessoa
PUT http://localhost:5128/api/pessoas/9
Content-Type: application/json

{
  "nome": "João Atualizado",
  "idade": 35,
  "enderecoId": 2
}

###

### Remover uma pessoa
DELETE http://localhost:5128/api/pessoas/1

###

### Atualizar um endereço
PUT http://localhost:5128/api/enderecos/1
Content-Type: application/json

{
  "rua": "Rua Nova",
  "cidade": "Rio de Janeiro",
  "estado": "RJ"
}

###

### Remover um endereço
DELETE http://localhost:5128/api/enderecos/1
